table _Measures
	lineageTag: 6c255b35-7717-4655-9f90-465875f8b5e6

	measure 'Count of Tickets' = COUNTROWS(fct_tickets_data)
		formatString: 0
		lineageTag: 70541429-e846-4fb3-a521-02b9b306b1db

	measure 'Total Tickets' = COUNT('fct_tickets_data'[Ticket ID])
		lineageTag: 122b7d4a-7706-48bb-9343-419a5f12017e

	measure 'Open Tickets' = CALCULATE(COUNT('fct_tickets_data'[Ticket ID]), 'fct_tickets_data'[Status] = "Open")
		lineageTag: 321f0fcf-d809-4845-826b-5d23b49a310a

	measure 'Resolved Tickets' = CALCULATE(COUNT('fct_tickets_data'[Ticket ID]), 'fct_tickets_data'[Status] = "Resolved")
		lineageTag: 3d48cebc-5eba-4d25-844c-ab8dd5a7cee4

	measure 'Avg Resolution Time (days)' = AVERAGEX(FILTER('fct_tickets_data', NOT(ISBLANK('fct_tickets_data'[Resolution Date]))), DATEDIFF('fct_tickets_data'[Date], 'fct_tickets_data'[Resolution Date], DAY))
		lineageTag: 001253f9-981f-4f56-a35e-ee7c23c1b143

	measure 'High Priority Tickets' = CALCULATE(COUNT('fct_tickets_data'[Ticket ID]), 'fct_tickets_data'[Priority] = "High")
		lineageTag: a826d4fe-ccf8-485d-b23d-bd5a5b5cf7ca

	measure '% Resueltos en SLA' = DIVIDE(CALCULATE(COUNTROWS('fct_tickets_data'), 'fct_tickets_data'[SLA Met] = "Yes"), COUNTROWS('fct_tickets_data'))
		lineageTag: 52d2d33f-dcd6-4122-ac30-f966547dba8c

	column Column
		isHidden
		formatString: 0
		lineageTag: d67eba11-d161-433a-8e44-2a96815279bd
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 0d46766bcdce45ffbd52e6d910739f91

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

